spring.application.name=codigoabierto

server.port=7070

spring.thymeleaf.cache=false

spring.datasource.url=jdbc:mysql://localhost:3306/codigo_abierto_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# NO crear/modificar tablas - usar las existentes
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# No ejecutar scripts SQL automáticamente
spring.sql.init.mode=never